version: 2

# Deshabilitar completamente el sistema de construcción
disable_use_build_env: true

# No usar ningún sistema de construcción
formats: []

# Configurar la documentación como solo lectura
docs_dir: docs

# Deshabilitar Python
python:
  install: []
  use_system_site_packages: false

# Configuración de la página de inicio
html_static_path: ["docs"]

# No instalar dependencias
build:
  os: ubuntu-22.04
  tools: {}
  jobs:
    post_create_environment: []
    pre_build: []
    build: []
    post_build: []